//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_demo48_網站加入服務參考使用WCF服務.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.I網站加入服務參考使用WCF服務")]
    public interface I網站加入服務參考使用WCF服務 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I網站加入服務參考使用WCF服務/Add", ReplyAction="http://tempuri.org/I網站加入服務參考使用WCF服務/AddResponse")]
        double Add(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I網站加入服務參考使用WCF服務/Add", ReplyAction="http://tempuri.org/I網站加入服務參考使用WCF服務/AddResponse")]
        System.Threading.Tasks.Task<double> AddAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I網站加入服務參考使用WCF服務/Subtract", ReplyAction="http://tempuri.org/I網站加入服務參考使用WCF服務/SubtractResponse")]
        double Subtract(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I網站加入服務參考使用WCF服務/Subtract", ReplyAction="http://tempuri.org/I網站加入服務參考使用WCF服務/SubtractResponse")]
        System.Threading.Tasks.Task<double> SubtractAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I網站加入服務參考使用WCF服務/Multiply", ReplyAction="http://tempuri.org/I網站加入服務參考使用WCF服務/MultiplyResponse")]
        double Multiply(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I網站加入服務參考使用WCF服務/Multiply", ReplyAction="http://tempuri.org/I網站加入服務參考使用WCF服務/MultiplyResponse")]
        System.Threading.Tasks.Task<double> MultiplyAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I網站加入服務參考使用WCF服務/Divide", ReplyAction="http://tempuri.org/I網站加入服務參考使用WCF服務/DivideResponse")]
        double Divide(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I網站加入服務參考使用WCF服務/Divide", ReplyAction="http://tempuri.org/I網站加入服務參考使用WCF服務/DivideResponse")]
        System.Threading.Tasks.Task<double> DivideAsync(double a, double b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface I網站加入服務參考使用WCF服務Channel : CS_demo48_網站加入服務參考使用WCF服務.ServiceReference1.I網站加入服務參考使用WCF服務, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class I網站加入服務參考使用WCF服務Client : System.ServiceModel.ClientBase<CS_demo48_網站加入服務參考使用WCF服務.ServiceReference1.I網站加入服務參考使用WCF服務>, CS_demo48_網站加入服務參考使用WCF服務.ServiceReference1.I網站加入服務參考使用WCF服務 {
        
        public I網站加入服務參考使用WCF服務Client() {
        }
        
        public I網站加入服務參考使用WCF服務Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public I網站加入服務參考使用WCF服務Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public I網站加入服務參考使用WCF服務Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public I網站加入服務參考使用WCF服務Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Add(double a, double b) {
            return base.Channel.Add(a, b);
        }
        
        public System.Threading.Tasks.Task<double> AddAsync(double a, double b) {
            return base.Channel.AddAsync(a, b);
        }
        
        public double Subtract(double a, double b) {
            return base.Channel.Subtract(a, b);
        }
        
        public System.Threading.Tasks.Task<double> SubtractAsync(double a, double b) {
            return base.Channel.SubtractAsync(a, b);
        }
        
        public double Multiply(double a, double b) {
            return base.Channel.Multiply(a, b);
        }
        
        public System.Threading.Tasks.Task<double> MultiplyAsync(double a, double b) {
            return base.Channel.MultiplyAsync(a, b);
        }
        
        public double Divide(double a, double b) {
            return base.Channel.Divide(a, b);
        }
        
        public System.Threading.Tasks.Task<double> DivideAsync(double a, double b) {
            return base.Channel.DivideAsync(a, b);
        }
    }
}
